### ISSUE TITLE
Iridium with uBlock Origin leaks filter lists

### ISSUE THREAD

**Issue by danielcra** [iridium-browser/tracker#163]
Iridium with uBlock Origin leaks filter lists, see https://browserleaks.com/proxy
In Firefox this has been fixed some time ago; although I am not sure whether the fix is in FF or if the uBlock version for Firefox contains the fix while the version for Chrome does not.

**Comment by iffin2l** [comment]
Leaking here too. Tested on Waterfox and Firefox and it has been fixed

**Comment by DutchPete** [comment]
The leak still exist today, 2 years later !!!! This is a privacy issue, which is 1 of the most important points Iridium was developed for, so how come this is left unattended ?????????

**Comment by DutchPete** [comment]
> Leaking here too. Tested on Waterfox and Firefox and it has been fixed

No, Mozilla has not fixed it either - Firefox 67.0.4.

**Comment by souldanger** [comment]
...it leaks in all current browsers as of July 2019... regardless as to what addons or extensions you use, some filter lists are leaking...
Seems like a general problem and not specific to IridiumBrowser.

**Comment by DutchPete** [comment]
@souldanger Thanks for your feedback.
