### ISSUE TITLE
MacOS version 61.0 fails to launch on 10.12.6

### ISSUE THREAD

**Issue by iur-kaia** [iridium-browser/tracker#174]
When you try to launch new version a system dialog pops up. It tells: 
"Iridium can't be opened. You should move it to trash." 

Searching in the internet gives this https://apple.stackexchange.com/questions/262355/xxx-cant-be-opened-you-should-move-it-to-trash-for-flash-projector-applicat

If you try to check codesigning:

```
$ spctl --assess /Applications/Iridium.app/
/Applications/Iridium.app/: CSSMERR_TP_CERT_REVOKED
```

Further internet search gives suggestions to disable gatekeeper for this app or to remove signature which I think is risky.

Could you please check how you sign the new build?

EDIT:
```
$ pkgutil --check-signature ~/Downloads/iridium_browser_61.0.0_osx_x64.dmg 
Package "iridium_browser_61.0.0_osx_x64.dmg":
   Status: package is invalid (checksum did not verify)
```

**Comment by fkr** [comment]
Thanks for the report - am following upon this soon.

**Comment by fkr** [comment]
There will be an updated - correctly signed - macOS version shortly.

**Comment by medozas** [comment]
The updated and correctly signed macOS version has been uploaded. Please check again- the issue should now be resolved. closing.

**Comment by iur-kaia** [comment]
https://downloads.iridiumbrowser.de/macosx/ still shows the old file with old last modified date.
If you download iridium_browser_61.0.0_osx_x64.dmg and verify you still get `Status: package is invalid (checksum did not verify)`
@medozas @fkr Could you please check that you have updated file on file server?

**Comment by iur-kaia** [comment]
Hmm, package utility still says that package is invalid but you still can run the app. Thanks for fast response.
