### ISSUE TITLE
In Facebook:First click of Share browse jumps

### ISSUE THREAD

**Issue by PaulRehel** [iridium-browser/tracker#307]
Ever since facebook change UI: When first clicking on "Share" the page jumps to the top of the page.

Iridium | 2019.04 (Developer Build) Built on Ubuntu 16.04, running on Ubuntu 18.04 (64-bit)
Revision | e82a658d8159cabbd4938c1660f9bb00b4a82a23-refs/branch-heads/3683@{#902}
OS | Linux
JavaScript | V8 7.3.492.27
Flash | (Disabled)
User Agent | Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/2019.04 Iridium/2019.04 Safari/537.36 Chrome/73.0.0.0
Command Line | /usr/lib/iridium-browser/iridium-browser --enable-pinch --flag-switches-begin --ignore-gpu-blacklist --flag-switches-end --file-url-path-alias=/gen=/usr/lib/iridium-browser/gen

**Comment by jengelh** [comment]
I cannot reproduce the behavior in 2020.04.81 or 2020.11.85, so I presume it is fixed.

**Comment by PaulRehel** [comment]
Just tried again.  It'a still happening.  If I find a way of screen recording it, will you except that download?  This is in Linux(Ubuntu 18.04) which only has 2019.04,
Repository for Debian-based systems
current version 2019.04.73 - outdated
(based on Chromium 73.0.3683.103)

**Comment by PaulRehel** [comment]
jengelh, this is for a Debian-based systems Ubuntu 18.04.  2020.04.81 and 2020.11.85 can't so easily, if at all, be used.
